# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from ..types.tts_provider import TtsProvider
from .http_client import AsyncHttpClient, HttpClient


class BaseClientWrapper:
    def __init__(
        self,
        *,
        api_key: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        tts_provider: typing.Optional[TtsProvider] = None,
        provider_params: typing.Optional[typing.Dict[str, typing.Any]] = None,
    ):
        self.api_key = api_key
        self._headers = headers
        self._base_url = base_url
        self._timeout = timeout
        self.tts_provider = tts_provider
        self.provider_params = provider_params

    def get_headers(self) -> typing.Dict[str, str]:
        headers: typing.Dict[str, str] = {
            "X-Fern-Language": "Python",
            **(self.get_custom_headers() or {}),
        }
        if self.api_key is not None:
            headers["x-api-key"] = self.api_key
        if self.tts_provider:
             headers["tts_provider"] = self.tts_provider
        # provider_params are not automatically added to headers
        return headers

    def get_custom_headers(self) -> typing.Optional[typing.Dict[str, str]]:
        return self._headers

    def get_base_url(self) -> str:
        return self._base_url

    def get_timeout(self) -> typing.Optional[float]:
        return self._timeout


class SyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        api_key: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        httpx_client: httpx.Client,
        tts_provider: typing.Optional[TtsProvider] = None,
        provider_params: typing.Optional[typing.Dict[str, typing.Any]] = None,
    ):
        super().__init__(
            api_key=api_key, 
            headers=headers, 
            base_url=base_url, 
            timeout=timeout, 
            tts_provider=tts_provider, 
            provider_params=provider_params
        )
        self.httpx_client = HttpClient(
            httpx_client=httpx_client,
            base_headers=self.get_headers,
            base_timeout=self.get_timeout,
            base_url=self.get_base_url,
        )


class AsyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        api_key: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        httpx_client: httpx.AsyncClient,
        tts_provider: typing.Optional[TtsProvider] = None,
        provider_params: typing.Optional[typing.Dict[str, typing.Any]] = None,
    ):
        super().__init__(
            api_key=api_key, 
            headers=headers, 
            base_url=base_url, 
            timeout=timeout, 
            tts_provider=tts_provider, 
            provider_params=provider_params
        )
        self._async_token = async_token
        self.httpx_client = AsyncHttpClient(
            httpx_client=httpx_client,
            base_headers=self.get_headers,
            base_timeout=self.get_timeout,
            base_url=self.get_base_url,
            async_base_headers=self.async_get_headers,
        )

    async def async_get_headers(self) -> typing.Dict[str, str]:
        headers = self.get_headers()
        if self._async_token is not None:
            token = await self._async_token()
            headers["Authorization"] = f"Bearer {token}"
        return headers
