# This file was auto-generated by Fern from our API Definition.

import typing

CreateStreamTtsRequestPayloadSpeechModel = typing.Union[
    typing.Literal["mars-pro", "mars-flash", "mars-instruct"], typing.Any
]
