# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .dictionary_term import DictionaryTerm
from .languages import Languages


class DictionaryWithTerms(UniversalBaseModel):
    id: int
    name: str
    description: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    last_edited_at: typing.Optional[dt.datetime] = None
    dictionary_terms: typing.Optional[typing.List[DictionaryTerm]] = None
    languages: typing.Optional[typing.List[Languages]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
