# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .languages import Languages
from .stream_category import StreamCategory


class SourceStream(UniversalBaseModel):
    language: Languages
    url: str
    category: typing.Optional[StreamCategory] = None
    passphrase: typing.Optional[str] = None
    streamid: typing.Optional[str] = None
    number_of_streams: typing.Optional[int] = None
    audio_stream: typing.Optional[int] = None
    background_audio_stream: typing.Optional[int] = None
    latency: typing.Optional[int] = None
    relay_input: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
