# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class StreamTtsVoiceSettings(UniversalBaseModel):
    """
    Advanced settings for voice customization.

    Attributes:
        enhance_reference_audio_quality: Whether to enhance the quality of the
            reference audio before cloning. Defaults to False.
    """

    enhance_reference_audio_quality: typing.Optional[bool] = None
    maintain_source_accent: typing.Optional[bool] = None
    apply_ref_loudness_norm: typing.Optional[bool] = False

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
