# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SubtitleFormattingOptions(UniversalBaseModel):
    max_segment_duration_in_seconds: typing.Optional[float] = None
    min_segment_duration_in_seconds: typing.Optional[float] = None
    max_characters_in_segment: typing.Optional[int] = None
    max_reading_speed_in_cps: typing.Optional[float] = None
    min_gap_between_segments_in_frames: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
