# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.languages import Languages
from ..types.orchestrator_pipeline_call_result import OrchestratorPipelineCallResult
from ..types.orchestrator_pipeline_result import OrchestratorPipelineResult
from ..types.subtitle_formatting_options import SubtitleFormattingOptions
from ..types.transcript_data_type import TranscriptDataType
from ..types.transcript_file_format import TranscriptFileFormat
from .raw_client import AsyncRawSubtitlesClient, RawSubtitlesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubtitlesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubtitlesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubtitlesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubtitlesClient
        """
        return self._raw_client

    def create_subtitle(
        self,
        *,
        media_url: str,
        source_language: Languages,
        target_languages: typing.Sequence[Languages],
        project_name: typing.Optional[str] = OMIT,
        project_description: typing.Optional[str] = OMIT,
        folder_id: typing.Optional[int] = OMIT,
        transcription_mode: typing.Optional[typing.Literal["fast", "slow"]] = "fast",
        formatting_options: typing.Optional[typing.Union[SubtitleFormattingOptions, typing.Dict[str, typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrchestratorPipelineCallResult:
        """
        Parameters
        ----------
        media_url : str

        source_language : Languages

        target_languages : typing.Sequence[Languages]

        project_name : typing.Optional[str]

        project_description : typing.Optional[str]

        folder_id : typing.Optional[int]

        transcription_mode : typing.Optional[typing.Literal["fast", "slow"]]
            Transcription mode: `fast` (default) or `slow`.

        formatting_options : typing.Optional[typing.Union[SubtitleFormattingOptions, typing.Dict[str, typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrchestratorPipelineCallResult
            Successful Response

        Examples
        --------
        from camb import CambApi

        client = CambApi(
            api_key="YOUR_API_KEY",
        )
        client.subtitles.create_subtitle(
            media_url="https://example.com/video.mp4",
            source_language=1,
            target_languages=[1],
        )
        """
        _response = self._raw_client.create_subtitle(
            media_url=media_url,
            source_language=source_language,
            target_languages=target_languages,
            project_name=project_name,
            project_description=project_description,
            folder_id=folder_id,
            transcription_mode=transcription_mode,
            formatting_options=formatting_options,
            request_options=request_options,
        )
        return _response.data

    def get_subtitle_task_status(
        self,
        task_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrchestratorPipelineResult:
        """
        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrchestratorPipelineResult
            Successful Response

        Examples
        --------
        from camb import CambApi

        client = CambApi(
            api_key="YOUR_API_KEY",
        )
        client.subtitles.get_subtitle_task_status(
            task_id="task_id",
        )
        """
        _response = self._raw_client.get_subtitle_task_status(task_id, request_options=request_options)
        return _response.data

    def get_subtitle_result(
        self,
        run_id: typing.Optional[int],
        *,
        format_type: typing.Optional[TranscriptFileFormat] = None,
        data_type: typing.Optional[TranscriptDataType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        run_id : typing.Optional[int]

        format_type : typing.Optional[TranscriptFileFormat]

        data_type : typing.Optional[TranscriptDataType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from camb import CambApi

        client = CambApi(
            api_key="YOUR_API_KEY",
        )
        client.subtitles.get_subtitle_result(
            run_id=1,
        )
        """
        _response = self._raw_client.get_subtitle_result(
            run_id, format_type=format_type, data_type=data_type, request_options=request_options
        )
        return _response.data

    def get_subtitle_result_for_language(
        self,
        run_id: typing.Optional[int],
        language: Languages,
        *,
        format_type: typing.Optional[TranscriptFileFormat] = None,
        data_type: typing.Optional[TranscriptDataType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        run_id : typing.Optional[int]

        language : Languages

        format_type : typing.Optional[TranscriptFileFormat]

        data_type : typing.Optional[TranscriptDataType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from camb import CambApi

        client = CambApi(
            api_key="YOUR_API_KEY",
        )
        client.subtitles.get_subtitle_result_for_language(
            run_id=1,
            language=1,
        )
        """
        _response = self._raw_client.get_subtitle_result_for_language(
            run_id, language, format_type=format_type, data_type=data_type, request_options=request_options
        )
        return _response.data

    def get_subtitle_results(
        self,
        *,
        run_ids: typing.Sequence[int],
        format_type: typing.Optional[TranscriptFileFormat] = None,
        data_type: typing.Optional[TranscriptDataType] = None,
        traceparent: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Parameters
        ----------
        run_ids : typing.Sequence[int]
            Between 2 and 5 unique run IDs. For a single run, use
            ``get_subtitle_result`` instead.

        format_type : typing.Optional[TranscriptFileFormat]

        data_type : typing.Optional[TranscriptDataType]

        traceparent : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        from camb import CambApi

        client = CambApi(
            api_key="YOUR_API_KEY",
        )
        client.subtitles.get_subtitle_results(
            run_ids=[12345, 12346],
        )
        """
        _response = self._raw_client.get_subtitle_results(
            run_ids=run_ids,
            format_type=format_type,
            data_type=data_type,
            traceparent=traceparent,
            request_options=request_options,
        )
        return _response.data


class AsyncSubtitlesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubtitlesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubtitlesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubtitlesClient
        """
        return self._raw_client

    async def create_subtitle(
        self,
        *,
        media_url: str,
        source_language: Languages,
        target_languages: typing.Sequence[Languages],
        project_name: typing.Optional[str] = OMIT,
        project_description: typing.Optional[str] = OMIT,
        folder_id: typing.Optional[int] = OMIT,
        transcription_mode: typing.Optional[typing.Literal["fast", "slow"]] = "fast",
        formatting_options: typing.Optional[typing.Union[SubtitleFormattingOptions, typing.Dict[str, typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrchestratorPipelineCallResult:
        """
        Parameters
        ----------
        media_url : str

        source_language : Languages

        target_languages : typing.Sequence[Languages]

        project_name : typing.Optional[str]

        project_description : typing.Optional[str]

        folder_id : typing.Optional[int]

        transcription_mode : typing.Optional[typing.Literal["fast", "slow"]]
            Transcription mode: `fast` (default) or `slow`.

        formatting_options : typing.Optional[typing.Union[SubtitleFormattingOptions, typing.Dict[str, typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrchestratorPipelineCallResult
            Successful Response

        Examples
        --------
        import asyncio

        from camb import AsyncCambApi

        client = AsyncCambApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subtitles.create_subtitle(
                media_url="https://example.com/video.mp4",
                source_language=1,
                target_languages=[1],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_subtitle(
            media_url=media_url,
            source_language=source_language,
            target_languages=target_languages,
            project_name=project_name,
            project_description=project_description,
            folder_id=folder_id,
            transcription_mode=transcription_mode,
            formatting_options=formatting_options,
            request_options=request_options,
        )
        return _response.data

    async def get_subtitle_task_status(
        self,
        task_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrchestratorPipelineResult:
        """
        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrchestratorPipelineResult
            Successful Response

        Examples
        --------
        import asyncio

        from camb import AsyncCambApi

        client = AsyncCambApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subtitles.get_subtitle_task_status(
                task_id="task_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subtitle_task_status(task_id, request_options=request_options)
        return _response.data

    async def get_subtitle_result(
        self,
        run_id: typing.Optional[int],
        *,
        format_type: typing.Optional[TranscriptFileFormat] = None,
        data_type: typing.Optional[TranscriptDataType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        run_id : typing.Optional[int]

        format_type : typing.Optional[TranscriptFileFormat]

        data_type : typing.Optional[TranscriptDataType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from camb import AsyncCambApi

        client = AsyncCambApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subtitles.get_subtitle_result(
                run_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subtitle_result(
            run_id, format_type=format_type, data_type=data_type, request_options=request_options
        )
        return _response.data

    async def get_subtitle_result_for_language(
        self,
        run_id: typing.Optional[int],
        language: Languages,
        *,
        format_type: typing.Optional[TranscriptFileFormat] = None,
        data_type: typing.Optional[TranscriptDataType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        run_id : typing.Optional[int]

        language : Languages

        format_type : typing.Optional[TranscriptFileFormat]

        data_type : typing.Optional[TranscriptDataType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from camb import AsyncCambApi

        client = AsyncCambApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subtitles.get_subtitle_result_for_language(
                run_id=1,
                language=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subtitle_result_for_language(
            run_id, language, format_type=format_type, data_type=data_type, request_options=request_options
        )
        return _response.data

    async def get_subtitle_results(
        self,
        *,
        run_ids: typing.Sequence[int],
        format_type: typing.Optional[TranscriptFileFormat] = None,
        data_type: typing.Optional[TranscriptDataType] = None,
        traceparent: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Parameters
        ----------
        run_ids : typing.Sequence[int]
            Between 2 and 5 unique run IDs. For a single run, use
            ``get_subtitle_result`` instead.

        format_type : typing.Optional[TranscriptFileFormat]

        data_type : typing.Optional[TranscriptDataType]

        traceparent : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from camb import AsyncCambApi

        client = AsyncCambApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subtitles.get_subtitle_results(
                run_ids=[12345, 12346],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subtitle_results(
            run_ids=run_ids,
            format_type=format_type,
            data_type=data_type,
            traceparent=traceparent,
            request_options=request_options,
        )
        return _response.data
